apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.operator.scope.namespace }}
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
metadata:
  name: k8s-nim-operator-role
  labels:
  {{- include "k8s-nim-operator.labels" . | nindent 4 }}
rules:
{{- if not .Values.operator.scope.namespace }}
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - pods/log
  - pods/eviction
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemoguardrails
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemoguardrails/finalizers
  verbs:
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemoguardrails/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemodatastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemodatastores/finalizers
  verbs:
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nemodatastores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimcaches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimcaches/finalizers
  verbs:
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimcaches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimpipelines/finalizers
  verbs:
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimpipelines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimservices/finalizers
  verbs:
  - update
- apiGroups:
  - apps.nvidia.com
  resources:
  - nimservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.operator.scope.namespace }}
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: k8s-nim-operator-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8s-nim-operator
    app.kubernetes.io/part-of: k8s-nim-operator
  {{- include "k8s-nim-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.operator.scope.namespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: k8s-nim-operator-role
subjects:
- kind: ServiceAccount
  name: k8s-nim-operator
  namespace: {{ .Release.Namespace }}
